name: pr 

on: 
  pull_request:
    branches:
      - main

name: Docker Compose Actions Workflow
on: 
  push:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Compose
        run: docker-compose up -d
      
      - name: Run Tests
        run: docker run container:test ./build/bin/test