name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Run Tests
        run: docker-compose -f ./docker/docker-compose.yml up test
