name: Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Notifications
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        uses: Ilshidur/action-discord@0.3.0
        with:
          args: "{{EVENT_PAYLOAD.repository.full_name}}
                 has new changes on main. See latest at: https://github.com/harris-jacob/gb-emulator"
