name: Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Notifications
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

        uses: Ilshidur/action-discord@0.3.0
        with:
          args: "{{EVENT_PAYLOAD.repository.full_name}} update: Commit {{github.event.head_commit.message}} has been merged to master."
